try:
    1/0
except Exception as X:
    print('Following exception occured: ',X)